### ISSUE TITLE
“Who is born on January 10, 1938?”

### ISSUE THREAD

**Issue by ProgVal** [ProjetPP/PPP-QuestionParsing-Grammatical#110]
http://askplatyp.us/?lang=en&q=Who+is+born+on+January+10%2C+1938%3F

**Comment by Ezibenroc** [comment]
Actually, it produces `(January 10 1938, birth, ?)`, which is a good triple (the problem is that we do not have a database containing the list of births for this day, we could use Wikipedia for this: [here](https://en.wikipedia.org/wiki/1938#Births) or [here](https://en.wikipedia.org/wiki/Category:1938_births)).

This might be changed by #106, by one of the following:
* `(January 10 1938, birth, ?)`
* `(?, birth date, January 10 1938)`
* `(January 10 1938, birth, ?)∪(?, birth date, January 10 1938)`

**Comment by yhamoudi** [comment]
Fixed in https://github.com/ProjetPP/PPP-QuestionParsing-Grammatical/tree/reverse_predicates
