### ISSUE TITLE
“What is 802.11?”

### ISSUE THREAD

**Issue by ProgVal** [ProjetPP/PPP-QuestionParsing-Grammatical#113]
parsed as `(?,definition,802.11)`

http://askplatyp.us/?lang=en&q=What+is+802.11%3F

**Comment by Ezibenroc** [comment]
The problem come from the Stanford parser. This is even worse for “What is P=NP?”.
We could try to train it on such cases. 
An other solution would be to do some preprocessing: if there is a part of the sentence with numbers or symbols like `=`, then handle it as if it was within quotations.

**Comment by yhamoudi** [comment]
(Partially) Fixed in https://github.com/ProjetPP/PPP-QuestionParsing-Grammatical/tree/reverse_predicates (but the problem comes from the stanford parser)

Possible solution for such cases: apply the algorithm used with quotations:
  - identify "strange" entities (an entity = a sequence of letters without space, "strange" = contain a strange symbol : `.`, `=`, ...). Ex: `802.11`, `P=NP`,...
  - replace them by a random string
  - parse with the stanford parser
  - replace the random string by the initial word

If someone wants to implement this, please do it in branch `reverse_predicates` in file `preprocessingMerge.py`.

**Comment by yhamoudi** [comment]
See https://github.com/ProjetPP/PPP-QuestionParsing-Grammatical/issues/118

**Comment by Ezibenroc** [comment]
+1 for this solution.
But this does not concern this branch. You should do one pull request per
problem to avoid huge modifications.

**Comment by yhamoudi** [comment]
> But this does not concern this branch. You should do one pull request per

I will remove the advice once the branch will be merged. It's just to avoid that someone implement the solution in master before, otherwise there will be a big conflict.
