### ISSUE TITLE
"who was Liz Taylor married to?"

### ISSUE THREAD

**Issue by Tpt** [ProjetPP/PPP-QuestionParsing-Grammatical#114]
It outputs an intersection instead of the simple triple (Liz Taylor, husband, ?): http://askplatyp.us/?lang=en&q=who+was+Liz+Taylor+married+to%3F

**Comment by yhamoudi** [comment]
It's almost good since the first element of the intersection is `(Liz Taylor, husband, ?)`. The problem comes from the dependency used by the stanford parser : `married -xcomp-> to` (i'm not sure it's a mistake from the stanford parser). Since `to` is a complement, we produce a second triple...

How to solve it:
  - build a map of the most common prepositions in english (to, of, by....)
  - in `preprocessingMerge.py`, for all edge `v -> p` (`v` is a verb and `p` a preposition), merge `p` into `v`.

@Ezibenroc If we want also to merge `v -prep_x-> y` into `v x -prep-> y`, how could we find the position of `x` into the initial sentence (`x` can contain several words, we need to find the position of each of them) ?

(please do such modifications directly on branch `reverse_predicates`)

**Comment by Ezibenroc** [comment]
I will have a look on Monday...

**Comment by yhamoudi** [comment]
Fixed https://github.com/ProjetPP/PPP-QuestionParsing-Grammatical/commit/9fb72771c53863ba95e52c71a0aca4635f3001b1
