### ISSUE TITLE
“work” given as predicate for “what did terry pratchett write?”

### ISSUE THREAD

**Issue by ProgVal** [ProjetPP/PPP-QuestionParsing-Grammatical#138]
It should not be a predicate (neither should “works”), because it does not make sense (and is an alias for “occupation” on Wikidata).

http://askplatyp.us/?lang=en&q=what+did+terry+pratchett+write%3F

**Comment by ProgVal** [comment]
And also, there is a regression because it used to be `(?, author, Terry Pratchett)`

**Comment by Ezibenroc** [comment]
`(?, author, Terry Pratchett)` is a subset of what we returns, since `author` is in the inverse predicate. There is no regression.

But I agree to remove `work` and `works`.

**Comment by yhamoudi** [comment]
I put them because they are properties used by wikidata to provide the books of an author (see http://www.wikidata.org/wiki/Property:P800 and http://www.wikidata.org/wiki/Q3335) but I will remove them if they are ambiguous.

> (?, author, Terry Pratchett) is a subset of what we returns, since author is in the inverse predicate. There is no regression.

Yes, it would be nice to display the reverse predicates too on the UI

**Comment by Ezibenroc** [comment]
We could use `notable works` instead.

**Comment by yhamoudi** [comment]
Fix https://github.com/ProjetPP/PPP-QuestionParsing-Grammatical/commit/3771506e6177a1a3bd257f95aaa3372d04d1b764

**Comment by ProgVal** [comment]
The Wikidata module does not support reverse-predicates, so the Platypus is broken on these searches :(

**Comment by yhamoudi** [comment]
I think it's the [only query](http://askplatyp.us/?lang=en&q=who+wrote+%22Dubliners%22) that appears in https://github.com/ProjetPP/PPP-WebUI/blob/master/questions.js and that cannot work without reverse predicates. We should remove it temporarily.

> so the Platypus is broken on these searches :(

yes it's sad, but we cannot hardcode this question into the question parsing module. I let you lobby @Tpt  so that reverse predicates are supported quickly by the wikidata module :)

**Comment by Tpt** [comment]
Support of reverse predicate is currently bocked by the fact that we need to be able to do fast queries (thing that WikidataQuery doesn't allow). I've nearly finished to implement queries into my custom EntityStore. The remaining things are to create indexes in the deployed database and to convert Wikidata module to use the EntityStore instead of Wikidata query.

So, if everything goes well (I'm not sure that MongoDB will be reactive enough with thousands of indexes) Wikidata module should be able to support reverse predicates within two weeks.

But if you want these things to go quicker, contributions are welcome!

**Comment by ProgVal** [comment]
In the meantime, I reverted the version of the Grammatical used by the Platypus to 0.6.1.

**Comment by yhamoudi** [comment]
If it's just for "what did terry pratchett write?", we lose more questions that what we win...

**Comment by ProgVal** [comment]
It's not just for Terry Pratchett
