### ISSUE TITLE
"date of birth of Barack Obama"

### ISSUE THREAD

**Issue by Tpt** [ProjetPP/PPP-QuestionParsing-Grammatical#64]
queries like: http://ppp.pony.ovh/?lang=en&q=date+of+birth+of+Barack+Obama

**Comment by yhamoudi** [comment]
This kind of queries is really difficult because we have to perform multiwords expressions (MWE) recognition if we want to parse it correctly. (from the grammatical point of view, `barack obama` and `birth` have __exactly__ the same role).

We didn't find efficient + easy to use tools that perform MWE recognition. However, it seems now that conceptnet could be used to perform this task. Indeed, if a MWE exists then it is a concept and it can be in conceptnet (`first president` is not in conceptnet, but  `prime minister` or `date of birth` are \o/). I think we could investigate this a little more. If conceptnet is powerful enough, here is what we can do to deal with MWE:
  - use conceptnet to find all the MWE in the input sentence
  - concatenate each MWE into a single word (same thing than with quotations). Be sure that it has no effect on the stanford parsing
  - parse with the stanford parser, run the usual algorithm

**Comment by yhamoudi** [comment]
The parsing of `date of birth of Barack Obama` is not good (same problem of "distributivity" than the example here: https://github.com/ProjetPP/PPP-QuestionParsing-Grammatical/issues/90).

However, let's assume the parsing was good, we will be able to produce `((Barack Obama, birth,?),date,?)`. Then we could use the same collapsing trick than here: https://github.com/ProjetPP/PPP-QuestionParsing-Grammatical/issues/85

(this solution is less powerful than detecting the multiwords expressions and merging them before using the stanford parser, but it is more likely to succeed)

**Comment by yhamoudi** [comment]
See https://github.com/ProjetPP/PPP-QuestionParsing-Grammatical/issues/123
